SEQUOIASQLMAINSTREAM-688 sdb_sql_ctl修改为 basename -bash的方式获取实际脚本名称

diff --git a/package/mysql/sdb_sql_ctl b/package/mysql/sdb_sql_ctl
--- a/package/mysql/sdb_sql_ctl
+++ b/package/mysql/sdb_sql_ctl
@@ -31,12 +31,13 @@ NEED_BACKUPLOG=false
 SQL_USER=sdbadmin
 SYS_CONF_FILE=""
 PROCESS_WAIT_TIME=5
+ME=$(basename "$0")
 
 function lack_para()
 {
    local para_name=$1
-   echo "sdb_sql_ctl: no parameter \"$para_name\" specified" >&2
-   echo 'Try "sdb_sql_ctl --help" for more information.'
+   echo "${ME}: no parameter \"$para_name\" specified" >&2
+   echo "Try '${ME} --help' for more information."
    exit 64
 }
 
@@ -44,8 +45,8 @@ function err_para()
 {
    local para_name=$1
    local para_value=$2
-   echo "sdb_sql_ctl: unrecognized $para_name \"$para_value\"" >&2
-   echo 'Try "sdb_sql_ctl --help" for more information.'
+   echo "${ME}: unrecognized $para_name \"$para_value\"" >&2
+   echo "Try '${ME} --help' for more information."
    exit 64
 }
 
@@ -56,8 +57,8 @@ function check_num_para()
 
    local regex='^[0-9]+$'
    if ! [[ "$para_value" =~ $regex ]]; then
-      echo "sdb_sql_ctl: invalid value for parameter \"$para_name\": \"$para_value\"" >&2
-      echo 'Try "sdb_sql_ctl --help" for more information.'
+      echo "${ME}: invalid value for parameter \"$para_name\": \"$para_value\"" >&2
+      echo "Try '${ME} --help' for more information."
       exit 64
    fi
 }
@@ -108,8 +109,8 @@ function check_opt_para()
    do
       case "$opt" in
          -V | --version | '-?' | --help )
-            echo "sdb_sql_ctl: parameter \"OPTIONS\" is forbidden to include \"$opt\"" >&2
-            echo 'Try "sdb_sql_ctl --help" for more information.'
+            echo "${ME}: parameter \"OPTIONS\" is forbidden to include \"$opt\"" >&2
+            echo "Try '${ME} --help' for more information."
             exit 64
             ;;
       esac
@@ -153,7 +154,7 @@ function check_user()
    local cur_user=`whoami`
    if [ "$cur_user" != "$SQL_USER" -a "$cur_user" != "root" ]
    then
-      echo "ERROR: sdb_sql_ctl $operate_mode requires SQLUSER [$SQL_USER] permission" >&2
+      echo "ERROR: ${ME} $operate_mode requires SQLUSER [$SQL_USER] permission" >&2
       exit 77
    fi
 }
@@ -771,19 +772,19 @@ function show_version()
 
 function build_help()
 {
-   echo "sdb_sql_ctl is a utility to initialize, start, stop, or control a SequoiaSQL-MySQL server."
+   echo "${ME} is a utility to initialize, start, stop, or control a SequoiaSQL-MySQL server."
    echo ""
    echo "Usage:"
-   echo "  sdb_sql_ctl listinst"
-   echo "  sdb_sql_ctl addinst    <INSTNAME> <-D DATADIR> [-l LOGFILE] [--print] [-p PORT] [-f PIDFILE] [-s SOCKETFILE] [-w PASSWORD]"
-   echo "  sdb_sql_ctl delinst    <INSTNAME> [--baklog]"
-   echo "  sdb_sql_ctl start      <INSTNAME>                           [--print]"
-   echo "  sdb_sql_ctl startall                                        [--print]"
-   echo "  sdb_sql_ctl stop       <INSTNAME>                           [--print]"
-   echo "  sdb_sql_ctl stopall                                         [--print]"
-   echo "  sdb_sql_ctl restart    <INSTNAME>                           [--print]"
-   echo "  sdb_sql_ctl status     [INSTNAME]"
-   echo "  sdb_sql_ctl chconf     <INSTNAME> [-p PORT] [-e LEVEL]                 [-a MAX-CON] [--sdb-conn-addr=ADDR] [--sdb-user=USER] [--sdb-passwd=PASSWD] [--sdb-auto-partition=BOOL] [--sdb-use-bulk-insert=BOOL] [--sdb-bulk-insert-size=SIZE] [--sdb-use-autocommit=BOOL] [--sdb-debug-log=BOOL]"
+   echo "  ${ME} listinst"
+   echo "  ${ME} addinst    <INSTNAME> <-D DATADIR> [-l LOGFILE] [--print] [-p PORT] [-f PIDFILE] [-s SOCKETFILE] [-w PASSWORD]"
+   echo "  ${ME} delinst    <INSTNAME> [--baklog]"
+   echo "  ${ME} start      <INSTNAME>                           [--print]"
+   echo "  ${ME} startall                                        [--print]"
+   echo "  ${ME} stop       <INSTNAME>                           [--print]"
+   echo "  ${ME} stopall                                         [--print]"
+   echo "  ${ME} restart    <INSTNAME>                           [--print]"
+   echo "  ${ME} status     [INSTNAME]"
+   echo "  ${ME} chconf     <INSTNAME> [-p PORT] [-e LEVEL]                 [-a MAX-CON] [--sdb-conn-addr=ADDR] [--sdb-user=USER] [--sdb-passwd=PASSWD] [--sdb-auto-partition=BOOL] [--sdb-use-bulk-insert=BOOL] [--sdb-bulk-insert-size=SIZE] [--sdb-use-autocommit=BOOL] [--sdb-debug-log=BOOL]"
    echo ""
    echo "Options:"
    echo "  -D DATADIR                       location of the database storage area"
@@ -809,7 +810,7 @@ function build_help()
 #Parse command line parameters
 test $# -eq 0 && { build_help && exit 64; }
 
-ARGS=`getopt -o hvD:l:p:s:f:e:a:w: --long help,version,print,baklog,sdb-conn-addr:,sdb-user:,sdb-passwd:,sdb-use-partition:,sdb-auto-partition:,sdb-use-bulk-insert:,sdb-bulk-insert-size:,sdb-use-autocommit:,sdb-debug-log: -n 'sdb_sql_ctl' -- "$@"`
+ARGS=`getopt -o hvD:l:p:s:f:e:a:w: --long help,version,print,baklog,sdb-conn-addr:,sdb-user:,sdb-passwd:,sdb-use-partition:,sdb-auto-partition:,sdb-use-bulk-insert:,sdb-bulk-insert-size:,sdb-use-autocommit:,sdb-debug-log: -n "${ME}" -- "$@"`
 ret=$?
 test $ret -ne 0 && exit $ret
 
@@ -945,7 +946,7 @@ case "$1" in
                mode=$1; shift 2;;
    chconf)     mode=$1
                if [ -z "$PORT" -a -z "$LOG_ERROR_VERBOSITY" -a -z "$MAX_CON" -a -z "$SDB_USER" -a -z "$SDB_PASSWD" -a -z "$SDB_AUTO_PARTITION" -a -z "$SDB_USE_BULK_INSERT" -a -z "$SDB_BULK_INSERT_SIZE" -a -z "$SDB_USE_AUTOCOMMIT" -a -z "$SDB_DEBUG_LOG" ]; then
-                  echo "sdb_sql_ctl: No configure specified." 
+                  echo "${ME}: No configure specified." 
                   exit 0
                   shift 1
                else
@@ -953,15 +954,15 @@ case "$1" in
                   shift 2
                fi
                ;;
-   *)          echo "sdb_sql_ctl: unrecognized operation mode \"$1\"" >&2
-               echo 'Try "sdb_sql_ctl --help" for more information.'
+   *)          echo "${ME}: unrecognized operation mode \"$1\"" >&2
+               echo "Try '${ME} --help' for more information."
                exit 64
                ;;
 esac
 
 if [ "$*" != "" ]; then
-   echo "sdb_sql_ctl: too many arguments: $*" >&2
-   echo 'Try "sdb_sql_ctl --help" for more information.'
+   echo "${ME}: too many arguments: $*" >&2
+   echo "Try '${ME} --help' for more information."
    exit 64
 fi
 
