SEQUOIASQLMAINSTREAM-951 修改sdb_sql_ctl工具错误描述.

diff --git a/package/mariadb/sdb_sql_ctl b/package/mariadb/sdb_sql_ctl
--- a/package/mariadb/sdb_sql_ctl
+++ b/package/mariadb/sdb_sql_ctl
@@ -149,7 +149,7 @@ function get_system_conf_file()
    then
       SYS_CONF_FILE=$file
    else
-      echo "ERROR: No system configure file exist in /etc/default" >&2
+      echo "[ERROR] Register configuration file in /etc/default/ does not exist" >&2
       exit 12
    fi
 }
