SEQUOIASQLMAINSTREAM-964 实例组功能错误输出优化

diff --git a/package/mariadb/sdb_sql_ctl b/package/mariadb/sdb_sql_ctl
--- a/package/mariadb/sdb_sql_ctl
+++ b/package/mariadb/sdb_sql_ctl
@@ -22,6 +22,11 @@
 #   20    fail to write file
 #   21    svcname isn't in range ( 0, 65536 )
 #   22    can not find configure file
+#   30    instance group name can't be empty
+#   31    instance already exists in instance group
+#   32    failed to remove instance from instance group
+#   33    failed to clear up instance group configuration
+#   34    failed to check if instance group exists
 #   64    command line usage error
 #   77    permission denied
 
@@ -959,6 +964,14 @@ function leave_inst_group()
    local inst_group_name=`cat $SQLDATA/auto.cnf | awk -F'#' '{print $1}' | grep "^\s*server_ha_inst_group_name"`
    inst_group_name=${inst_group_name#*=}
    test "${inst_group_name:0:1}" == '"' && inst_group_name=${inst_group_name:1:-1}
+
+   # check if the target instance group exists
+   local connection_str=`build_auth_string`
+   list_str=$($BIN_PATH/ha_inst_group_list --name=$INST_GROUP_NAME $connection_str 2>&1)
+   if [ $? != 0 ]; then
+      echo "$list_str"
+      exit 34
+   fi
 
    # check if current instance exists in instance group
    if [ "$inst_group_name" == "" ]; then
