SEQUOIASQLMAINSTREAM-1038 fix: sdb 未启动时，实例组启动失败提示用户看的日志文件路径不合理.

diff --git a/package/mariadb/sdb_sql_ctl b/package/mariadb/sdb_sql_ctl
--- a/package/mariadb/sdb_sql_ctl
+++ b/package/mariadb/sdb_sql_ctl
@@ -674,7 +674,7 @@ function start_inst()
       return 0
    elif [ $ret == 7 ]
    then
-      echo "ERROR: Fail to start, please verify log $CTL_LOG" >&2
+      echo "ERROR: Fail to start, please verify log $SQLLOG" >&2
       return 7
    else
       echo "ERROR: Fail to query status." >&2
